on:
  release:
    types: [published]

name: push-docker-image-release

jobs:
  push-docker-image-release:
    uses: anytypeio/any-sync-node/.github/workflows/push-docker-image-reusable.yml@ci
    with:
      release: ${{ github.event.release.tag_name }}
