on:
  release:
    types: [published]

name: push-docker-image-release

jobs:
  push-docker-image-release:
    uses: anyproto/any-sync-node/.github/workflows/push-docker-image-reusable.yml@main
    secrets: inherit
    with:
      release: ${{ github.event.release.tag_name }}
      dockerfile-cmd: /bin/any-sync-node -c /etc/any-sync-node/config.yml
