---
name: Searching for secrets

on:
  - push
  - pull_request

jobs:
  secret-scanner-reusable:
    uses: anyproto/shared-actions/.github/workflows/secret-scanner-reusable.yml@v1
    secrets: inherit # pass all secrets
